version: '3.9'
services:
  gamelib_db:
    image: "postgres:14.5-alpine"
    networks:
      database_net:
        aliases:
          - database_host
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: pg_isready -U admin -d postgres
      interval: 10s
      timeout: 30s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - database_net
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://admin:admin@database_host:5432/postgres?sslmode=disable", "up"]
    restart: "on-failure"
    depends_on:
      -  gamelib_db
    links:
      -  gamelib_db

  gamelib_app:
    build: ./
    command: ./app
    ports:
      - "8080:8080"
    depends_on:
      - gamelib_db

networks:
  database_net: