port: "8080"

db:
#    Docker-config
#    host: "db"
#    port: "5432"

    host: "localhost"
    port: "5400"
    username: "admin"
    password: "admin"
    dbname: "postgres"
    sslmode: "disable"